/*
 * generated by Xtext
 */
package net.blimster.gwt.threejs.wdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ThreeJsWrapperDescriptionLanguageRuntimeModule extends net.blimster.gwt.threejs.wdl.AbstractThreeJsWrapperDescriptionLanguageRuntimeModule {

}
