/*
* generated by Xtext
*/
package net.blimster.gwt.threejs.wdl.ui.contentassist;

import net.blimster.gwt.threejs.wdl.ui.contentassist.AbstractThreeJsWrapperDescriptionLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ThreeJsWrapperDescriptionLanguageProposalProvider extends AbstractThreeJsWrapperDescriptionLanguageProposalProvider {

}
