/*
 * generated by Xtext
 */
package net.blimster.gwt.threejs.wdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ThreeJsWrapperDescriptionLanguageUiModule extends net.blimster.gwt.threejs.wdl.ui.AbstractThreeJsWrapperDescriptionLanguageUiModule {
	public ThreeJsWrapperDescriptionLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
