/*
* generated by Xtext
*/
package net.blimster.gwt.threejs.wdl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ThreeJsWrapperDescriptionLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
