/*
 * generated by Xtext
 */
package net.blimster.gwt.threejs.wdl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ThreeJsWrapperDescriptionLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return net.blimster.gwt.threejs.wdl.ui.internal.ThreeJsWrapperDescriptionLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return net.blimster.gwt.threejs.wdl.ui.internal.ThreeJsWrapperDescriptionLanguageActivator.getInstance().getInjector("net.blimster.gwt.threejs.wdl.ThreeJsWrapperDescriptionLanguage");
	}
	
}
