/*
* generated by Xtext
*/
package net.blimster.gwt.threejs.wdl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.blimster.gwt.threejs.wdl.services.ThreeJsWrapperDescriptionLanguageGrammarAccess;

public class ThreeJsWrapperDescriptionLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ThreeJsWrapperDescriptionLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.blimster.gwt.threejs.wdl.parser.antlr.internal.InternalThreeJsWrapperDescriptionLanguageParser createParser(XtextTokenStream stream) {
		return new net.blimster.gwt.threejs.wdl.parser.antlr.internal.InternalThreeJsWrapperDescriptionLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ThreeJsWrapperDescriptionLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ThreeJsWrapperDescriptionLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
