/*
* generated by Xtext
*/
package net.blimster.gwt.threejs.wdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ThreeJsWrapperDescriptionLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("net/blimster/gwt/threejs/wdl/parser/antlr/internal/InternalThreeJsWrapperDescriptionLanguage.tokens");
	}
}
